/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    pages: Page;
    services: Service;
    'service-nodes': ServiceNode;
    'legal-documents': LegalDocument;
    categories: Category;
    media: Media;
    branches: Branch;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-nodes': ServiceNodesSelect<false> | ServiceNodesSelect<true>;
    'legal-documents': LegalDocumentsSelect<false> | LegalDocumentsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {
    settings: Setting;
    'payroll-config': PayrollConfig;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'payroll-config': PayrollConfigSelect<false> | PayrollConfigSelect<true>;
  };
  locale: 'vi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Bài viết của Trung tâm kiến thức. Lưu nháp để viết dở, bấm Xuất bản khi đăng.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Phần đuôi địa chỉ web, viết thường không dấu, nối bằng dấu gạch ngang. Ví dụ: gioi-thieu. ĐÃ ĐĂNG RỒI THÌ ĐỪNG ĐỔI — đổi là mọi link cũ hỏng và mất thứ hạng Google.
   */
  slug: string;
  /**
   * Ngày hiển thị trên bài và dùng để sắp xếp. Bỏ trống thì tự lấy thời điểm xuất bản.
   */
  publishedAt?: string | null;
  /**
   * Mỗi bài thuộc đúng một chuyên mục.
   */
  category: number | Category;
  /**
   * Ảnh đại diện trong danh sách bài. Nên ảnh ngang tỉ lệ 3:2.
   */
  cover?: (number | null) | Media;
  /**
   * Vài dòng giới thiệu hiện ở danh sách bài viết. Nên 1–2 câu.
   */
  excerpt?: string | null;
  /**
   * Soạn thảo như Word. Dán từ Word nên dùng Ctrl+Shift+V. Chèn ảnh bằng nút trên thanh công cụ, ảnh sẽ vào Thư viện ảnh.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Phần hiển thị trên Google và khi chia sẻ lên Facebook/Zalo. Bỏ trống thì hệ thống tự lấy tiêu đề và mô tả ngắn của bài.
   */
  seo?: {
    /**
     * Dòng chữ xanh trên Google. Nên 50–60 ký tự, có tên dịch vụ chính.
     */
    title?: string | null;
    /**
     * Đoạn mô tả dưới tiêu đề trên Google. Nên 120–160 ký tự.
     */
    description?: string | null;
    /**
     * Ảnh hiện khi dán link lên Facebook/Zalo. Nên 1200×630 px.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Nhóm bài viết của Trung tâm kiến thức. Mỗi bài viết thuộc một chuyên mục.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Phần đuôi địa chỉ web, viết thường không dấu, nối bằng dấu gạch ngang. Ví dụ: gioi-thieu. ĐÃ ĐĂNG RỒI THÌ ĐỪNG ĐỔI — đổi là mọi link cũ hỏng và mất thứ hạng Google.
   */
  slug: string;
  /**
   * Chuyên mục nằm ở cột nào trong menu Trung tâm kiến thức.
   */
  group: 'accounting' | 'legal-hr';
  /**
   * Vài dòng giới thiệu hiện ở đầu trang chuyên mục.
   */
  description?: string | null;
  /**
   * Số nhỏ hiện trước. Để 0 hết thì sắp theo tên.
   */
  order?: number | null;
  /**
   * Phần hiển thị trên Google và khi chia sẻ lên Facebook/Zalo. Bỏ trống thì hệ thống tự lấy tiêu đề và mô tả ngắn của bài.
   */
  seo?: {
    /**
     * Dòng chữ xanh trên Google. Nên 50–60 ký tự, có tên dịch vụ chính.
     */
    title?: string | null;
    /**
     * Đoạn mô tả dưới tiêu đề trên Google. Nên 120–160 ký tự.
     */
    description?: string | null;
    /**
     * Ảnh hiện khi dán link lên Facebook/Zalo. Nên 1200×630 px.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Kho ảnh và file PDF dùng chung cho cả website. Tải lên một lần rồi chọn lại ở bài viết, trang, dịch vụ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Tả ngắn nội dung ảnh, ví dụ "Nhân viên tư vấn khách hàng". Quan trọng cho SEO và người khiếm thị đọc màn hình.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Các trang cố định của website: Giới thiệu, Liên hệ, Dịch vụ chuyên ngành…
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Phần đuôi địa chỉ web, viết thường không dấu, nối bằng dấu gạch ngang. Ví dụ: gioi-thieu. ĐÃ ĐĂNG RỒI THÌ ĐỪNG ĐỔI — đổi là mọi link cũ hỏng và mất thứ hạng Google.
   */
  slug: string;
  /**
   * Ảnh lớn hiển thị trên cùng. Nên ảnh ngang, tối thiểu 1600 px chiều rộng.
   */
  heroImage?: (number | null) | Media;
  /**
   * Soạn thảo như Word. Bôi đen chữ để in đậm/đặt link. Dán từ Word nên dùng Ctrl+Shift+V để không mang theo định dạng lỗi.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Phần hiển thị trên Google và khi chia sẻ lên Facebook/Zalo. Bỏ trống thì hệ thống tự lấy tiêu đề và mô tả ngắn của bài.
   */
  seo?: {
    /**
     * Dòng chữ xanh trên Google. Nên 50–60 ký tự, có tên dịch vụ chính.
     */
    title?: string | null;
    /**
     * Đoạn mô tả dưới tiêu đề trên Google. Nên 120–160 ký tự.
     */
    description?: string | null;
    /**
     * Ảnh hiện khi dán link lên Facebook/Zalo. Nên 1200×630 px.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Các dịch vụ công ty cung cấp, hiển thị ở trang chủ và menu Dịch vụ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Phần đuôi địa chỉ web, viết thường không dấu, nối bằng dấu gạch ngang. Ví dụ: gioi-thieu. ĐÃ ĐĂNG RỒI THÌ ĐỪNG ĐỔI — đổi là mọi link cũ hỏng và mất thứ hạng Google.
   */
  slug: string;
  /**
   * Chọn một khoá icon có sẵn: chart, folder, search, document, finance, archive, growth. Bỏ trống hoặc gõ sai tên sẽ tự dùng icon mặc định, không vỡ giao diện.
   */
  icon?: string | null;
  /**
   * Số nhỏ hiện trước.
   */
  order?: number | null;
  /**
   * Ảnh minh hoạ hiện ở thẻ dịch vụ ngoài trang chủ và đầu trang chi tiết. Nên ảnh ngang tỉ lệ 3:2. Bỏ trống thì thẻ chỉ hiện icon như trước.
   */
  image?: (number | null) | Media;
  /**
   * 1–2 câu hiện ở thẻ dịch vụ ngoài trang chủ.
   */
  summary?: string | null;
  /**
   * Nội dung đầy đủ của trang dịch vụ. Soạn thảo như Word.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Phần hiển thị trên Google và khi chia sẻ lên Facebook/Zalo. Bỏ trống thì hệ thống tự lấy tiêu đề và mô tả ngắn của bài.
   */
  seo?: {
    /**
     * Dòng chữ xanh trên Google. Nên 50–60 ký tự, có tên dịch vụ chính.
     */
    title?: string | null;
    /**
     * Đoạn mô tả dưới tiêu đề trên Google. Nên 120–160 ký tự.
     */
    description?: string | null;
    /**
     * Ảnh hiện khi dán link lên Facebook/Zalo. Nên 1200×630 px.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Cây dịch vụ. Mục không chọn "Thuộc nhóm" là nhóm cấp cao nhất, hiện trên thanh menu. Mục có chọn là hạng mục con của nhóm đó.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-nodes".
 */
export interface ServiceNode {
  id: number;
  title: string;
  /**
   * Phần đuôi địa chỉ web, viết thường không dấu, nối bằng dấu gạch ngang. Ví dụ: gioi-thieu. ĐÃ ĐĂNG RỒI THÌ ĐỪNG ĐỔI — đổi là mọi link cũ hỏng và mất thứ hạng Google.
   */
  slug: string;
  /**
   * Bỏ trống = nhóm cấp cao nhất, hiện trên thanh menu. Chọn một mục = nằm bên trong mục đó.
   */
  parent?: (number | null) | ServiceNode;
  /**
   * Số nhỏ hiện trước. Để 0 hết thì sắp theo tên.
   */
  order?: number | null;
  /**
   * Khoá icon có sẵn: chart, folder, search, document, finance, archive, growth. Gõ sai thì dùng icon mặc định, không vỡ giao diện.
   */
  icon?: string | null;
  /**
   * Hiện ở thẻ ngoài trang chủ và đầu trang chi tiết. Nên ảnh ngang 3:2.
   */
  image?: (number | null) | Media;
  /**
   * Vài dòng hiện dưới tiêu đề và trong thẻ ngoài trang chủ.
   */
  summary?: string | null;
  /**
   * Dải số liệu dưới mô tả, ví dụ "7 / HẠNG MỤC", "03–05 / NGÀY LÀM VIỆC". Bỏ trống thì không hiện dải này.
   */
  heroStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Chọn từng khối cần dùng rồi kéo để đổi thứ tự. Không bắt buộc dùng đủ mọi khối.
   */
  body?:
    | (
        | {
            /**
             * Bỏ trống thì hiện "Bảng giá dịch vụ".
             */
            title?: string | null;
            rows?:
              | {
                  item: string;
                  scope?: string | null;
                  /**
                   * Ghi cả đơn vị, ví dụ "500.000 / tháng" hoặc "từ 3.000.000 / tháng". Đây là chữ, không phải số — để ghi được "liên hệ" hay "theo khối lượng".
                   */
                  fee?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Ví dụ: phí chưa gồm lệ phí nhà nước.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingTable';
          }
        | {
            /**
             * Ví dụ: Nhiệm vụ của công ty, Nhiệm vụ của khách hàng, Cam kết.
             */
            title: string;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bulletList';
          }
        | {
            title?: string | null;
            rows?:
              | {
                  /**
                   * Ví dụ: Yêu cầu chung, Thực hiện, Thời gian, Trả kết quả.
                   */
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fieldTable';
          }
        | {
            title?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
        | {
            label: string;
            /**
             * Ví dụ: /lien-he — hoặc địa chỉ đầy đủ nếu trỏ ra ngoài.
             */
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  /**
   * Phần hiển thị trên Google và khi chia sẻ lên Facebook/Zalo. Bỏ trống thì hệ thống tự lấy tiêu đề và mô tả ngắn của bài.
   */
  seo?: {
    /**
     * Dòng chữ xanh trên Google. Nên 50–60 ký tự, có tên dịch vụ chính.
     */
    title?: string | null;
    /**
     * Đoạn mô tả dưới tiêu đề trên Google. Nên 120–160 ký tự.
     */
    description?: string | null;
    /**
     * Ảnh hiện khi dán link lên Facebook/Zalo. Nên 1200×630 px.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Danh mục luật, nghị định, thông tư hiển thị ở trang Văn bản pháp luật. Chỉ dẫn link tới nguồn chính thức, không đăng lại file.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents".
 */
export interface LegalDocument {
  id: number;
  /**
   * Ví dụ: Luật Kế toán, Chế độ kế toán doanh nghiệp.
   */
  title: string;
  /**
   * Ví dụ: 88/2015/QH13, 200/2014/TT-BTC.
   */
  code: string;
  /**
   * Văn bản nằm ở tab nào trên trang.
   */
  group: 'ke-toan' | 'thue' | 'bhxh' | 'lao-dong' | 'dang-ky-kinh-doanh' | 'dau-tu' | 'thuong-mai';
  /**
   * Ví dụ: Quốc hội, Bộ Tài chính, Chính phủ.
   */
  issuer?: string | null;
  /**
   * Năm văn bản có hiệu lực, ví dụ 2017. Để chữ chứ không phải số để ghi được "đã hết hiệu lực" hay "sửa đổi 2021".
   */
  effectiveYear?: string | null;
  /**
   * Địa chỉ đầy đủ tới văn bản trên trang của cơ quan ban hành (bắt đầu bằng https://). Bỏ trống thì dòng đó không có link.
   */
  sourceUrl?: string | null;
  /**
   * Số nhỏ hiện trước trong nhóm.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Danh sách văn phòng hiển thị ở chân trang và trang Liên hệ. Chỉ Quản trị viên sửa được.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  city: string;
  /**
   * Ghi đầy đủ số nhà, đường, phường/xã, quận/huyện, tỉnh/thành.
   */
  address: string;
  /**
   * Ví dụ: 0243 123 4567. Bỏ trống thì chân trang tự ẩn dòng này.
   */
  phone?: string | null;
  /**
   * Bỏ trống thì chân trang tự ẩn dòng này.
   */
  email?: string | null;
  /**
   * Mở Google Maps, tìm địa chỉ, bấm Chia sẻ → Sao chép liên kết rồi dán vào đây. Không phải mã nhúng <iframe>.
   */
  mapUrl?: string | null;
  /**
   * Số nhỏ hiện trước. Trụ sở chính nên để 0.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Thông tin khách gửi qua form Liên hệ trên website. Gọi lại xong thì tick "Đã liên hệ lại".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  message?: string | null;
  /**
   * Tick sau khi đã gọi/gửi mail cho khách, để người khác khỏi gọi trùng.
   */
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tài khoản đăng nhập trang quản trị. Chỉ Quản trị viên mới thêm/sửa/xoá được.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Quản trị viên: toàn quyền, kể cả xoá và sửa cấu hình. Biên tập viên: chỉ viết và sửa nội dung, không xoá được gì.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-nodes';
        value: number | ServiceNode;
      } | null)
    | ({
        relationTo: 'legal-documents';
        value: number | LegalDocument;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  category?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  order?: T;
  image?: T;
  summary?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-nodes_select".
 */
export interface ServiceNodesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  order?: T;
  icon?: T;
  image?: T;
  summary?: T;
  heroStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  body?:
    | T
    | {
        pricingTable?:
          | T
          | {
              title?: T;
              rows?:
                | T
                | {
                    item?: T;
                    scope?: T;
                    fee?: T;
                    id?: T;
                  };
              note?: T;
              id?: T;
              blockName?: T;
            };
        bulletList?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fieldTable?:
          | T
          | {
              title?: T;
              rows?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richTextBlock?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents_select".
 */
export interface LegalDocumentsSelect<T extends boolean = true> {
  title?: T;
  code?: T;
  group?: T;
  issuer?: T;
  effectiveYear?: T;
  sourceUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  group?: T;
  description?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  city?: T;
  address?: T;
  phone?: T;
  email?: T;
  mapUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  message?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Thông tin dùng chung cho toàn website: logo, hotline, địa chỉ, mạng xã hội. Chỉ Quản trị viên sửa được.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Hiện ở tiêu đề trình duyệt và kết quả Google. Bỏ trống thì dùng tên mặc định của site.
   */
  siteName?: string | null;
  /**
   * Nên dùng file PNG nền trong suốt, cao tối thiểu 120 px.
   */
  logo?: (number | null) | Media;
  /**
   * Ảnh lớn cạnh slogan ở đầu trang chủ. Nên dùng ảnh ngang (tỉ lệ 3:2), rộng tối thiểu 1200 px. Để trống thì phần chữ tự giãn kín chiều ngang.
   */
  heroImage?: (number | null) | Media;
  /**
   * Câu ngắn dưới logo, ví dụ "Dịch vụ kế toán trọn gói".
   */
  tagline?: string | null;
  /**
   * Mã màu dạng #RRGGBB, mặc định #CC1420 — đỏ lấy đúng từ logo. Đổi màu này đổi toàn bộ nút và tiêu đề trên site, nên hỏi trước khi sửa.
   */
  primaryColor?: string | null;
  /**
   * Số chính hiện trên thanh đầu trang. Bỏ trống thì tự ẩn.
   */
  hotline?: string | null;
  /**
   * Số phụ, bỏ trống được.
   */
  hotline2?: string | null;
  email?: string | null;
  /**
   * Địa chỉ hiện ở chân trang. Chi nhánh khác khai ở mục Chi nhánh.
   */
  headOfficeAddress?: string | null;
  /**
   * Hiện cạnh email ở trang Liên hệ. Ví dụ: 08:00 – 17:30, thứ Hai – thứ Sáu. Bỏ trống thì không hiện dòng này.
   */
  workingHours?: string | null;
  taxCode?: string | null;
  /**
   * Hiện ở trang Giới thiệu, cột phải. Bỏ trống hết thì khối đó không hiện.
   */
  principles?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tên đầy đủ trên giấy phép kinh doanh, dùng cho dòng bản quyền.
   */
  companyName?: string | null;
  /**
   * Dán link đầy đủ, ví dụ https://facebook.com/tencongty. Bỏ trống thì ẩn icon.
   */
  facebook?: string | null;
  /**
   * Dán link đầy đủ.
   */
  tiktok?: string | null;
  /**
   * Dán link đầy đủ.
   */
  youtube?: string | null;
  /**
   * Dán link đầy đủ.
   */
  twitter?: string | null;
  /**
   * Ảnh mã QR để khách quét kết bạn Zalo. Ảnh vuông, nền trắng.
   */
  zaloQr?: (number | null) | Media;
  home?: {
    /**
     * Đoạn văn dưới slogan. Mặc định: "Dịch vụ kế toán trọn gói…". Slogan sửa ở tab Thương hiệu.
     */
    heroLead?: string | null;
    /**
     * Mặc định: Nhận tư vấn miễn phí
     */
    heroCta?: string | null;
    /**
     * Mặc định: Xem dịch vụ
     */
    heroCtaSecondary?: string | null;
    /**
     * Để trống cả mảng thì dùng 3 ô mặc định (Giảm thiểu / Nâng cao / Tối ưu). Thêm ô thứ 4 sẽ làm hàng bị lệch trên màn hình hẹp.
     */
    stats?:
      | {
          /**
           * Ví dụ: Giảm thiểu
           */
          value?: string | null;
          /**
           * Ví dụ: rủi ro về thuế và sổ sách
           */
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Bỏ trống thì dùng "Về " + tên site.
     */
    aboutTitle?: string | null;
    /**
     * Để trống cả mảng thì dùng 4 điểm mặc định. Biểu tượng chọn theo danh sách có sẵn.
     */
    aboutPoints?:
      | {
          icon?: ('award' | 'education' | 'legal' | 'phone') | null;
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Mặc định: Dịch vụ chuyên ngành
     */
    servicesTitle?: string | null;
    servicesSubtitle?: string | null;
    /**
     * Mặc định: Mạng lưới chi nhánh
     */
    branchesTitle?: string | null;
    branchesSubtitle?: string | null;
    /**
     * Mặc định: Trung tâm kiến thức
     */
    knowledgeTitle?: string | null;
    knowledgeSubtitle?: string | null;
    /**
     * Bỏ trống thì dùng "Kết nối với " + tên site.
     */
    socialTitle?: string | null;
    socialSubtitle?: string | null;
    /**
     * Mặc định: Cần tư vấn cho doanh nghiệp của bạn?
     */
    ctaTitle?: string | null;
    /**
     * Mặc định có nhắc "gọi trực tiếp" — nếu chưa điền Hotline ở tab Liên hệ thì nên sửa lại câu này cho khớp.
     */
    ctaSubtitle?: string | null;
    /**
     * Mặc định: Nhận tư vấn miễn phí
     */
    ctaButton?: string | null;
  };
  /**
   * 2–3 câu về công ty, hiện ở cột đầu chân trang.
   */
  aboutShort?: string | null;
  /**
   * Ví dụ: © 2026 Công ty TNHH ABC. Bảo lưu mọi quyền.
   */
  copyright?: string | null;
  /**
   * Bỏ trống thì dùng tiêu đề mặc định của cột đó.
   */
  footerHeadings?: {
    /**
     * Mặc định: Về chúng tôi
     */
    about?: string | null;
    /**
     * Mặc định: Liên kết nhanh
     */
    quickLinks?: string | null;
    /**
     * Mặc định: Bài viết gần đây
     */
    recentPosts?: string | null;
    /**
     * Mặc định: Liên hệ
     */
    contact?: string | null;
    /**
     * Mặc định: Theo dõi chúng tôi
     */
    followUs?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Số liệu luật dùng cho công cụ tính lương Gross ↔ Net tại /cong-cu/tinh-luong: giảm trừ gia cảnh, biểu thuế TNCN, tỷ lệ và trần bảo hiểm, lương tối thiểu vùng. Sửa ở đây là trang tính lương đổi theo ngay, không cần lập trình viên. Chỉ Quản trị viên sửa được.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-config".
 */
export interface PayrollConfig {
  id: number;
  /**
   * Mức giảm trừ cho chính người nộp thuế, trừ khỏi thu nhập trước khi tính thuế. Mặc định 15.500.000 đ/tháng (186 triệu/năm) theo Nghị quyết 110/2025/UBTVQH15, áp dụng từ kỳ tính thuế 2026.
   */
  personalDeduction: number;
  /**
   * Mức giảm trừ cho MỖI người phụ thuộc đã đăng ký (con nhỏ, cha mẹ già…). Mặc định 6.200.000 đ/tháng theo Nghị quyết 110/2025/UBTVQH15.
   */
  dependentDeduction: number;
  /**
   * Biểu thuế 5 bậc theo Luật Thuế thu nhập cá nhân 2025 (Luật 109/2025/QH15), hiệu lực 01/01/2026 cho thu nhập từ tiền lương. Tính LŨY TIẾN TỪNG PHẦN: mỗi bậc chỉ áp thuế suất cho phần thu nhập nằm trong bậc đó, không áp một thuế suất cho toàn bộ. Các dòng phải xếp tăng dần theo ngưỡng; dòng cuối bỏ trống ngưỡng nghĩa là bậc cao nhất không giới hạn.
   */
  taxBrackets: {
    /**
     * Ngưỡng TRÊN của bậc này, tính trên thu nhập TÍNH THUẾ (đã trừ bảo hiểm và giảm trừ gia cảnh). BỎ TRỐNG ở dòng cuối cùng = bậc cao nhất, không có trần.
     */
    upTo?: number | null;
    /**
     * Nhập theo đơn vị phần trăm: gõ 5 nghĩa là 5%, không gõ 0.05. Phải trong khoảng 0–100.
     */
    rate: number;
    id?: string | null;
  }[];
  /**
   * CHỈ phần NGƯỜI LAO ĐỘNG chịu, tổng 10,5% — đây là phần trừ vào lương. Phần doanh nghiệp đóng (21,5%) KHÔNG trừ vào lương nên không khai ở đây. Căn cứ: Luật Bảo hiểm xã hội 2024 (số 41/2024/QH15), Nghị định 158/2025/NĐ-CP, Nghị định 188/2025/NĐ-CP, từ 01/01/2026.
   */
  insuranceRates: {
    /**
     * Phần người lao động đóng, mặc định 8%. Nhập 8 nghĩa là 8%. Áp trên lương đóng bảo hiểm nhưng không vượt "Trần đóng BHXH và BHYT" bên dưới.
     */
    social: number;
    /**
     * Phần người lao động đóng, mặc định 1,5%. Nhập 1.5 (dùng dấu chấm thập phân). Dùng chung trần với BHXH.
     */
    health: number;
    /**
     * Phần người lao động đóng, mặc định 1%. Lưu ý BHTN dùng TRẦN RIÊNG, tính theo lương tối thiểu vùng — xem tab "Vùng lương" chứ không dùng trần BHXH/BHYT.
     */
    unemployment: number;
  };
  /**
   * ⚠️ SỐ NÀY CHƯA ĐƯỢC XÁC MINH — cần kế toán của khách xác nhận trước khi công bố trang. Lương cao hơn mức này thì BHXH và BHYT DỪNG ở mức này, không đóng thêm. Mặc định 46.800.000 đ = 20 × mức tham chiếu 2.340.000 đ. Có nguồn khác nêu 50.600.000 đ (từ 01/07/2026); dự án chọn 46.800.000 đ vì căn cứ "20 lần mức tham chiếu" rõ ràng hơn. Xác nhận xong thì sửa lại ô này.
   */
  insuranceCap: number;
  /**
   * Trần đóng BHTN = số này × lương tối thiểu của VÙNG người dùng chọn (căn cứ khác với trần BHXH/BHYT ở trên). Mặc định 20. Ví dụ Vùng I: 20 × 5.310.000 = 106.200.000 đ/tháng.
   */
  unemploymentCapMultiplier: number;
  /**
   * Lương tối thiểu 4 vùng theo Nghị định 293/2025/NĐ-CP, áp dụng 2026. Dùng để tính TRẦN đóng bảo hiểm thất nghiệp theo vùng người dùng chọn trên trang tính lương.
   */
  regions: {
    /**
     * Vùng theo phân loại của Nghị định lương tối thiểu vùng. Mỗi vùng chỉ khai một dòng.
     */
    code: 'I' | 'II' | 'III' | 'IV';
    /**
     * Mặc định: Vùng I 5.310.000 đ · Vùng II 4.730.000 đ · Vùng III 4.140.000 đ · Vùng IV 3.700.000 đ.
     */
    minWage: number;
    id?: string | null;
  }[];
  /**
   * Mốc hiệu lực của bộ số ở trên. Hiện công khai trên trang tính lương để người dùng biết đang áp luật mốc nào. Nên viết dạng 2026-01-01.
   */
  effectiveFrom: string;
  /**
   * Danh sách văn bản pháp luật làm căn cứ cho các số ở trên. Hiện công khai trên trang tính lương để người dùng tự đối chiếu. Mỗi căn cứ một dòng. Sửa số ở các tab khác thì nhớ cập nhật lại dòng căn cứ tương ứng ở đây.
   */
  legalBasis: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  heroImage?: T;
  tagline?: T;
  primaryColor?: T;
  hotline?: T;
  hotline2?: T;
  email?: T;
  headOfficeAddress?: T;
  workingHours?: T;
  taxCode?: T;
  principles?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  companyName?: T;
  facebook?: T;
  tiktok?: T;
  youtube?: T;
  twitter?: T;
  zaloQr?: T;
  home?:
    | T
    | {
        heroLead?: T;
        heroCta?: T;
        heroCtaSecondary?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        aboutTitle?: T;
        aboutPoints?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
              id?: T;
            };
        servicesTitle?: T;
        servicesSubtitle?: T;
        branchesTitle?: T;
        branchesSubtitle?: T;
        knowledgeTitle?: T;
        knowledgeSubtitle?: T;
        socialTitle?: T;
        socialSubtitle?: T;
        ctaTitle?: T;
        ctaSubtitle?: T;
        ctaButton?: T;
      };
  aboutShort?: T;
  copyright?: T;
  footerHeadings?:
    | T
    | {
        about?: T;
        quickLinks?: T;
        recentPosts?: T;
        contact?: T;
        followUs?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payroll-config_select".
 */
export interface PayrollConfigSelect<T extends boolean = true> {
  personalDeduction?: T;
  dependentDeduction?: T;
  taxBrackets?:
    | T
    | {
        upTo?: T;
        rate?: T;
        id?: T;
      };
  insuranceRates?:
    | T
    | {
        social?: T;
        health?: T;
        unemployment?: T;
      };
  insuranceCap?: T;
  unemploymentCapMultiplier?: T;
  regions?:
    | T
    | {
        code?: T;
        minWage?: T;
        id?: T;
      };
  effectiveFrom?: T;
  legalBasis?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}